[package]
name = "temocr"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
image = "0.25.5"
lexopt = "0.3.0"
ocrs = "0.9.0"
rten = "0.13"
rten-tensor = "0.14.1"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
winit = "0.30.5"
xcap = "0.0.14"
